## Work<ness app ##

ui <- navbarPage(
  title = div(img(src = "https://trafforddatalab.github.io/assets/logo/trafforddatalab_logo.svg", height="25", width="99"), 
              "Work<ness app"), windowTitle = "Work<ness app",
  tabPanel(title = "Cluster map",
           div(class="shinyContainer",
               tags$head(includeCSS("styles_base.css"), includeCSS("styles_shiny.css"), includeCSS("styles_map.css"),
                         tags$style(HTML("table.imd td:nth-child(2), table.imd td:nth-child(3) { text-align: right; }"))),
               leafletOutput("cluster_map", width = "100%", height = "100%"),
               absolutePanel(id = "shinyControls", class = "panel panel-default controls", fixed = TRUE, draggable = TRUE,
                             h4("Choose a local authority"),
                             selectInput(inputId = "la",
                                         label = NULL,
                                         choices = c("Greater Manchester", levels(df$lad17nm)),
                                         selected = "Greater Manchester"),
                             h4("and a measure"),
                             radioButtons(inputId = "measure",
                                          label = NULL,
                                          choices = c("Residents claiming JSA or Universal Credit",
                                                      "Working-age adults with no qualifications",
                                                      "Households with lone parent not in employment",
                                                      "Social rented households"),
                                          selected = "Residents claiming JSA or Universal Credit"),
                             hr(),
                             uiOutput("info")))),
  tabPanel(title = "Charts",
           fluidPage(
             sidebarLayout(
               sidebarPanel(width = 3,
                            uiOutput("choose_area"),
                            checkboxInput("multiple", label = "or multiple areas", value = FALSE),
                            conditionalPanel(
                              condition="input.multiple==true",
                              h6("Output options"),
                              checkboxInput("facet", label = "Facet by area", value = FALSE))),
               mainPanel(plotOutput("ggplot_plot", width = "100%", height = "300px"),
                         br(),
                         DT::dataTableOutput("area_table"),
                         br(),
                         downloadButton("downloadData", "Download data"))))),
  tabPanel(title = "Isochrone map",
           div(class="shinyContainer",
               tags$head(includeCSS("styles_base.css"), includeCSS("styles_shiny.css"), includeCSS("styles_map.css"),
                         tags$style(HTML(".leaflet-container {cursor:crosshair !important;}",
                                         "table.imd td:nth-child(2), table.imd td:nth-child(3) { text-align: right; }"))),
               leafletOutput("isochrone_map", width = "100%", height = "100%"),
               absolutePanel(id = "shinyControls", class = "panel panel-default controls", fixed = TRUE, draggable = TRUE,
                             h4("Choose an isochrone unit"),
                             radioButtons(inputId = "unit",
                                          label = NULL,
                                          choices = c("Distance" = "distance", "Travel time" = "time"),
                                          selected = "distance"),
                             conditionalPanel(
                               condition = "input.unit == 'time'",
                               selectInput(inputId = "mode",
                                           label = NULL,
                                           choices = c("Bike" = "cycling-regular",
                                                       "Car" = "driving-car", 
                                                       "Walk" = "foot-walking"),
                                           selected = "foot-walking"),
                               sliderInput("time_slider", label = h5("Range (minutes)"), min = 5, max = 30, value = 5, step = 5, ticks = FALSE, post = " minutes")),
                             uiOutput("range"),
                             br(),
                             actionButton("reset",
                                          label = "Clear isochrones"),
                             br(),br(),
                             tags$small("© Powered by ", tags$a(href="https://openrouteservice.org/", "openrouteservice")))),
  tabPanel(title = "About", 
           fluidRow(
             column(8, offset = 1,
                    includeMarkdown("about.md"), style = "color:#212121")))
)
