jcplus_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", jcplus$name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", jcplus$address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", jcplus$postcode, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)

probation_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", probation$name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Type</td>",
  "<td>", probation$type, "</td>",
  "</tr>",
  "<tr>",
  "<td>Address</td>",
  "<td>", probation$address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", probation$postcode, "</td>",
  "</tr>",
  "<tr>",
  "<td>Contact</td>",
  "<td>", probation$telephone, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)

gp_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", gp$name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", gp$address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", gp$postcode, "</td>",
  "</tr>",
  "<td>Contact</td>",
  "<td>", gp$tel, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)

food_bank_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", food_bank$name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", food_bank$address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", food_bank$post_code, "</td>",
  "</tr>",
  "<tr>",
  "<td>Opening times</td>",
  "<td>", food_bank$opening_times, "</td>",
  "</tr>",
  "<tr>",
  "<td>Contact</td>",
  "<td>", food_bank$contact, "</td>",
  "</tr>",
  "<tr>",
  "<td>Website</td>",
  "<td><a href'", food_bank$website, "' target='_blank'>", food_bank$website, "</a></td>",
  "</tr>",
  "</table>",
  "</div>"
)

betting_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", betting$name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", betting$address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", betting$postcode, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)