jcplus_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", jcplus$Name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", jcplus$Address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", jcplus$Postcode, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)

probation_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", probation$Name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Type</td>",
  "<td>", probation$Type, "</td>",
  "</tr>",
  "<tr>",
  "<td>Address</td>",
  "<td>", probation$Address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", probation$Postcode, "</td>",
  "</tr>",
  "<tr>",
  "<td>Contact</td>",
  "<td>", probation$Telephone, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)

gp_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", gp$Name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", gp$Address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", gp$Postcode, "</td>",
  "</tr>",
  "<td>Contact</td>",
  "<td>", gp$Telephone, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)

food_bank_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", food_bank$Name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", food_bank$Address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", food_bank$Postcode, "</td>",
  "</tr>",
  "<tr>",
  "<td>Opening times</td>",
  "<td>", food_bank$Opening.times, "</td>",
  "</tr>",
  "<tr>",
  "<td>Contact</td>",
  "<td>", food_bank$Contact, "</td>",
  "</tr>",
  "<tr>",
  "<td>Website</td>",
  "<td><a href'", food_bank$Website, "' target='_blank'>", food_bank$Website, "</a></td>",
  "</tr>",
  "</table>",
  "</div>"
)

gambling_popup = ~paste0(
  "<div class='popupContainer'>",
  "<h5>", gambling$Name, "</h5>",
  "<table class='popupLayout'>",
  "<tr>",
  "<td>Address</td>",
  "<td>", gambling$Address, "</td>",
  "</tr>",
  "<tr>",
  "<td>Postcode</td>",
  "<td>", gambling$Postcode, "</td>",
  "</tr>",
  "</table>",
  "</div>"
)